#!/usr/bin/env bash
# This script is displaying the content of the current directory in a list format.
for file in *; do
	if [[ $file == .* ]]; then
		continue
	fi
	name=$(echo $file | cut -d'-' -f2-)
	echo $name
done
